### ISSUE TITLE
Division by zero crashes on v2.2.0

### ISSUE THREAD

**Issue by Wojtaz0w** [sosauce/CuteCalc#13]
FATAL EXCEPTION: main
Process: com.sosauce.cutecalc, PID: 28626
v2.l: Division by zero
	at v2.d.a(SourceFile:51)
	at v2.d.I(SourceFile:69)
	at v2.n.a(SourceFile:1)
	at q2.a.A(SourceFile:927)
	at androidx.compose.ui.platform.q0.a(SourceFile:179)
	at androidx.compose.ui.platform.q0.W(SourceFile:177)
	at w2.o.e(SourceFile:7)
	at w2.o.d(SourceFile:1)
	at w2.r.a(SourceFile:76)
	at w2.r.s(SourceFile:52)
	at f.e.f(SourceFile:23)
	at f.e.W(SourceFile:524)
	at i.v1.g(SourceFile:134)
	at e3.a.c(SourceFile:1)
	at s3.a0.U(SourceFile:1)
	at s3.h.m(SourceFile:95)
	at s3.h.x(SourceFile:41)
	at s3.h.c(SourceFile:17)
	at w0.b0.y0(SourceFile:53)
	at w0.b0.X(SourceFile:1)
	at h.z.X(SourceFile:7)
	at w0.g.e(SourceFile:175)
	at w0.g.e(SourceFile:154)
	at w0.g.e(SourceFile:154)
	at w0.g.e(SourceFile:154)
	at w0.h.e(SourceFile:26)
	at t.b0.c(SourceFile:208)
	at androidx.compose.ui.platform.AndroidComposeView.C(SourceFile:79)
	at androidx.compose.ui.platform.AndroidComposeView.j(SourceFile:214)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(SourceFile:81)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3123)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2804)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:490)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1908)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4421)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:448)
	at android.view.View.dispatchPointerEvent(View.java:15928)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7247)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7037)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6435)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6623)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6466)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6680)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6439)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6466)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6439)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9436)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9387)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9356)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9562)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:162)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8190)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
	Suppressed: s3.e0: [androidx.compose.ui.platform.y1@336d7ee, w.f@438a48f, o1{Cancelling}@3dbd31c, w0@2939b25]

https://paste.crdroid.net/qrpuiV

**Comment by sosauce** [comment]
Fixed in [v2.2.1](https://github.com/sosauce/CuteCalc/releases/tag/v2.2.1)
